apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: mai
data:
  config.yaml: |
    domain: ratelimit
    descriptors:
      - key: PATH
        value: "/be"
        rate_limit:
            unit: minute
            requests_per_unit: 10

  # config.yaml: |
  #   domain: my-ratelimit
  #   descriptors:
  #       # Any descriptor with the remote address set, gets a rate limit of 10 req/min
  #     - key: remote_address
  #       rate_limit:
  #         unit: minute
  #         requests_per_unit: 10
